# Generated by Django 4.0 on 2022-03-08 06:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import librarian.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('nationality', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=75, unique=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=30)),
                ('details', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('which_edition', models.CharField(max_length=10)),
                ('price_in_Rs', models.IntegerField()),
                ('cover', models.ImageField(blank=True, upload_to='static/covers')),
                ('pdf', models.FileField(blank=True, upload_to='static/pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='ISBN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarian.edition')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('address', models.CharField(max_length=1024)),
                ('telephone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=75, unique=True)),
                ('alternative_telephone', models.CharField(blank=True, max_length=15)),
                ('alternative_email', models.EmailField(blank=True, max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_joined', models.CharField(max_length=4)),
                ('branch', models.CharField(choices=[('BEX', 'BEX'), ('BCT', 'BCT'), ('BCE', 'BCE'), ('BEI', 'BEI')], max_length=6)),
                ('roll_no', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Other', 'Other')], max_length=6)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=75, unique=True)),
                ('address', models.CharField(max_length=1024)),
                ('issued_count', models.IntegerField(default='0')),
                ('fine_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(default=librarian.models.get_expiry)),
                ('returned_status', models.BooleanField(default=False)),
                ('returned_date', models.DateTimeField(auto_now=True, null=True)),
                ('fine', models.IntegerField(blank=True, null=True)),
                ('isbn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='librarian.isbn')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='librarian.student')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.ManyToManyField(to='librarian.Author')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarian.publisher')),
            ],
        ),
        migrations.AddField(
            model_name='edition',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarian.title'),
        ),
    ]
