# Generated by Django 4.0 on 2022-04-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='fine',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='issued_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
