# Generated by Django 4.0 on 2022-04-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0002_alter_transaction_fine_alter_transaction_issued_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='issued_count',
            field=models.IntegerField(default=0),
        ),
    ]
